/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ztesoft_bss_zsmart_ucc_cc_common_utils_Number2RegularHelper */

#ifndef _Included_com_ztesoft_bss_zsmart_ucc_cc_common_utils_Number2RegularHelper
#define _Included_com_ztesoft_bss_zsmart_ucc_cc_common_utils_Number2RegularHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ztesoft_bss_zsmart_ucc_cc_common_utils_Number2RegularHelper
 * Method:    number2Regular
 * Signature: ([I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ztesoft_bss_zsmart_ucc_cc_common_utils_Number2RegularHelper_number2Regular
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_ztesoft_bss_zsmart_ucc_cc_common_utils_Number2RegularHelper
 * Method:    test
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ztesoft_bss_zsmart_ucc_cc_common_utils_Number2RegularHelper_test
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
